### ISSUE TITLE
please add some hero and header

### ISSUE THREAD

**Issue by FaruqRahmadani** [FaruqRahmadani/ProfileWebsite#3]
please help to create some hero and header to my index :) 

thanks
Faruq

**Comment by buddhikac96** [comment]
I'll take that. Happy to contribute.

**Comment by FaruqRahmadani** [comment]
ok thanks man :) happy coding :)

**Comment by jofftiquez** [comment]
May I ask what you meant by "hero"?

**Comment by viveksdf** [comment]
Can I add another hero too?

**Comment by vaibhavvijay9** [comment]
Please host it on GitHub pages, so that people can see it live.Thanks.
